[experiment]
name = "pgais-pilot"
task = "inference"

[data]
input = "data/prompts-lite-dataset.parquet"
output = "outputs"

[compute]
location = "remote"
url = "https://genai.rcac.purdue.edu/api/chat/completions"
max_concurrency = 20
requests_per_minute = 19

[model]
path = "pgais-lite-models.csv"
num_samples = 50
temperature = 0.7
seed = 542026
